version: '3'

services:
  chats_db:
    container_name: chats_database
    image: postgres:16
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
